openapi: 3.1.1
info:
  title: Planner API
  description: | 
    API for the Planner application allowing users to view and manage their tasks and schedules.
  version: 1.0.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
security:
  - apiToken: []
servers:
- url: http://localhost:3000/v1
  description: Local development server
- url: https://api-planner.ivan-b.com/v1
  description: Production server
- url: https://api-planner.bdgn.me/v1
  description: Staging server for testing
paths: 
  /events:
    get:
      operationId: getEvents
      summary: Get all events
      description: Retrieve a list of all events in the planner.
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Bad Request - The request was invalid or cannot be processed
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ProblemDetails'

        '401':
          description: Unauthorized - API token is missing or invalid
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error - An error occurred while processing the request
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ProblemDetails'

components:
  securitySchemes:
    apiToken:
      description: userId for API access
      type: apiKey
      name: user-id
      in: header
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the event
        summary:
          type: string
          description: Summary of the event
        description:
          type: string
          description: Detailed description of the event
        start:  
          type: string
          format: date-time
          description: Start time of the event
        end:
          type: string
          format: date-time
          description: End time of the event
        location:
          type: string
          description: Location of the event
        color:
          type: string
          description: Color code for the event

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          description: A URI reference that identifies the problem type
        title:
          type: string
          description: A short, human-readable summary of the problem type
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
